add_-latomic_to_ghc-prim
commit ce3897ffd6e7c8b8f36b8e920168bac8c7f836ae
Author: Ilias Tsitsimpis <iliastsi@debian.org>
Date:   Tue Sep 18 17:45:17 2018 +0200

    Fix check whether GCC supports __atomic_ builtins
    
    Summary:
    C11 atomics are never used because:
    
    * The program used for checking whether GCC supports
    __atomic_ builtins fails with the following error:
    
    ```
      error: size mismatch in argument 2 of `__atomic_load`
       int test(int *x) { int y; __atomic_load(&x, &y, __ATOMIC_SEQ_CST); return x; }
    ```
    
    * There is a typo when checking if CONF_GCC_SUPPORTS__ATOMICS equals YES,
    resulting in PRIM_CFLAGS and PRIM_EXTRA_LIBRARIES never being set.
    
    Reviewers: bgamari
    
    Reviewed By: bgamari
    
    Subscribers: rwbarton, erikd, carter
    
    Differential Revision: https://phabricator.haskell.org/D5154


Gbp-Pq: Name add_-latomic_to_ghc-prim